use_frameworks!

platform :ios, '12.0'

target 'khenshinClientIos_Example' do
  pod 'khenshinClientIos', :path => '../'

  target 'khenshinClientIos_Tests' do
    inherit! :search_paths

    
  end
end
