use_frameworks!

platform :ios, '13.0'

target 'KhipuClientIOS_Example' do
  pod 'KhipuClientIOS', :path => '../'

  target 'KhipuClientIOS_Tests' do
    inherit! :search_paths

    pod 'ViewInspector', '0.10.3'
  end
end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                # Enable previews for all pods
                config.build_settings['ENABLE_PREVIEWS'] = 'YES'
            end
        end
    end
    
    # Fix for SwiftUI Previews with CocoaPods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_PREVIEWS'] = 'YES'
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] ||= ['$(inherited)', '@executable_path/Frameworks', '@loader_path/Frameworks']
      end
    end
end
