use_frameworks!

platform :ios, '13.0'

target 'KhipuClientIOS_Example' do
  pod 'KhipuClientIOS', :path => '../'

  target 'KhipuClientIOS_Tests' do
    inherit! :search_paths

    pod 'ViewInspector', '0.10.1'
  end
end


post_install do |installer|
  UI.puts "== Listado de targets en Pods =="
    installer.pods_project.targets.each { |t| UI.puts "  • #{t.name}" }
    
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                
                if ['KhenshinSecureMessage', 'KHTweetNacl', 'CTweetNacl', 'TweetNacl', 'KhipuClientIOS'].include?(target.name)
                  config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
                  # Additional settings to resolve module dependencies
                  config.build_settings['SWIFT_ENABLE_INCREMENTAL_COMPILATION'] = 'NO'
                  config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
                end
            end
        end
    end
end
